---

root: true

extends:
  - 'airbnb-base'

env:
  browser: true
  node: true
  jest: true

rules:
  no-console: 0
  new-cap:
    - error
    - properties: false
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - req
        - reply
